[logging]
file = "server.log"
format = "Uri: {uri}, Method: {method}, Status: {status}, Duration: {response-time}, Time: {request-time}"

[tls]
p12 = "identity.p12"

[server]
port = 8080
# domain = localhost

[configs]
secrets = "secrets.toml"

[sessions]
duration = 604800 # Seconds in one week